version: 2
meta:
  test_defaults: &test_defaults
    working_directory: /go/src/github.com/alphagov/paas-rds-broker
    steps:
      - checkout
      - run:
          name: install ginkgo cli
          command: |
            cd "vendor/github.com/onsi/ginkgo/ginkgo"
            go install
      - run:
          command: ginkgo -r --skipPackage=ci
          environment:
            POSTGRESQL_PASSWORD: abc123
jobs:
  default:
    <<: *test_defaults
    docker:
      - image: circleci/golang:1.12
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_PASSWORD: abc123
          POSTGRES_INITDB_ARGS: "--auth-host=md5"
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
  postgres-10:
    <<: *test_defaults
    docker:
      - image: circleci/golang:1.12
      - image: circleci/postgres:10.5-alpine
        environment:
          POSTGRES_PASSWORD: abc123
          POSTGRES_INITDB_ARGS: "--auth-host=md5"
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
workflows:
  version: 2
  all_db_versions:
    jobs:
      - default
      - postgres-10
